spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/exp_lim
    username: yanalexn
    password: yan
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true

